port: 7880

bind_addresses:
  - 0.0.0.0

keys:
  devkey: 7b783c52a32944b2b1d4e76f59cb03ea

rtc:
  udp_port: 7880
  tcp_port: 7881

redis:
  address: 127.0.0.1:6379

sip:
  enabled: true

logging:
  level: info